/*
 * This file is generated by jOOQ.
*/
package com.uzykj.jooq.data;


import com.uzykj.jooq.data.tables.Message;
import com.uzykj.jooq.data.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Springboot extends SchemaImpl {

    private static final long serialVersionUID = -353180614;

    /**
     * The reference instance of <code>springboot</code>
     */
    public static final Springboot SPRINGBOOT = new Springboot();

    /**
     * The table <code>springboot.message</code>.
     */
    public final Message MESSAGE = com.uzykj.jooq.data.tables.Message.MESSAGE;

    /**
     * The table <code>springboot.user</code>.
     */
    public final User USER = com.uzykj.jooq.data.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Springboot() {
        super("springboot", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Message.MESSAGE,
            User.USER);
    }
}
