/*
 * This file is generated by jOOQ.
*/
package com.uzykj.jooq.data;


import com.uzykj.jooq.data.tables.Message;
import com.uzykj.jooq.data.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in springboot
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springboot.message</code>.
     */
    public static final Message MESSAGE = com.uzykj.jooq.data.tables.Message.MESSAGE;

    /**
     * The table <code>springboot.user</code>.
     */
    public static final User USER = com.uzykj.jooq.data.tables.User.USER;
}
