/*
 * This file is generated by jOOQ.
*/
package com.uzykj.jooq.data.tables.daos;


import com.uzykj.jooq.data.tables.Message;
import com.uzykj.jooq.data.tables.records.MessageRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageDao extends DAOImpl<MessageRecord, com.uzykj.jooq.data.tables.pojos.Message, Integer> {

    /**
     * Create a new MessageDao without any configuration
     */
    public MessageDao() {
        super(Message.MESSAGE, com.uzykj.jooq.data.tables.pojos.Message.class);
    }

    /**
     * Create a new MessageDao with an attached configuration
     */
    public MessageDao(Configuration configuration) {
        super(Message.MESSAGE, com.uzykj.jooq.data.tables.pojos.Message.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.uzykj.jooq.data.tables.pojos.Message object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchById(Integer... values) {
        return fetch(Message.MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.uzykj.jooq.data.tables.pojos.Message fetchOneById(Integer value) {
        return fetchOne(Message.MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>sender IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchBySender(String... values) {
        return fetch(Message.MESSAGE.SENDER, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchByPhone(String... values) {
        return fetch(Message.MESSAGE.PHONE, values);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchByTime(LocalDateTime... values) {
        return fetch(Message.MESSAGE.TIME, values);
    }

    /**
     * Fetch records that have <code>message IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchByMessage(String... values) {
        return fetch(Message.MESSAGE.MESSAGE_, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.Message> fetchByUserId(Integer... values) {
        return fetch(Message.MESSAGE.USER_ID, values);
    }
}
