/*
 * This file is generated by jOOQ.
*/
package com.uzykj.jooq.data.tables.daos;


import com.uzykj.jooq.data.tables.User;
import com.uzykj.jooq.data.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.uzykj.jooq.data.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.uzykj.jooq.data.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.uzykj.jooq.data.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.uzykj.jooq.data.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.uzykj.jooq.data.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByAge(Integer... values) {
        return fetch(User.USER.AGE, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByPhone(String... values) {
        return fetch(User.USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByAddress(String... values) {
        return fetch(User.USER.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>job IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByJob(String... values) {
        return fetch(User.USER.JOB, values);
    }

    /**
     * Fetch records that have <code>other IN (values)</code>
     */
    public List<com.uzykj.jooq.data.tables.pojos.User> fetchByOther(String... values) {
        return fetch(User.USER.OTHER, values);
    }
}
